# Generated by Django 3.0.5 on 2020-04-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(default='content', max_length=200),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
